name: version-module

on: [push, pull_request]

jobs:
  version-module:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v2

      - run: npm ci
      - run: npx playwright install-deps
      # This script automatically fails if the version module is not up-to-date.
      - run: npm run update-version-module
